name: YouBackup
version: 1.0.0
author: Kelgors
main: me.kelgors.ubackup.YouBackupPlugin
api-version: 1.16
softdepend: [ Vault ]
commands:
  youbackup:
    description: youbackup base command
    usage: /youbackup <subcommand>
    aliases: yb
permissions:
  youbackup.*:
    description: Access to all uBackup commands
  youbackup.help:
    description: Can show uBackup help
  youbackup.now:
    description: Can perform a backup now