name: YouBackup
version: 1.0.0
author: Kelgors
main: me.kelgors.youbackup.YouBackupPlugin
api-version: 1.13
softdepend: [ Vault ]
commands:
  youbackup:
    description: YouBackup base command
    usage: /youbackup (help|reload|profile <profile> [info|enable|disable|now])
    aliases: yb
    permission: youbackup.use
permissions:
  youbackup.*:
    description: Access to all YouBackup commands
  youbackup.help:
    description: Can display YouBackup help
  youbackup.reload:
    description: Can reload the YouBackup configuration
  youbackup.profile.*:
    description: Can perform any operation on any profile
  youbackup.profile.<profile>.*:
    description: Can perform any operation on given profile
  youbackup.profile.<profile>.now:
    description: Can perform a backup profile now
  youbackup.profile.<profile>.disable:
    description: Can disable a backup profile
  youbackup.profile.<profile>.enable:
    description: Can enable a backup profile
  youbackup.profile.<profile>.info:
    description: Can display information about the backup profile